export interface TrackedCreatorSeed {
  readonly name: string;
  readonly youtube_handle: string;
  readonly subscribers: string;
  readonly focus: string;
}

export const TRACKED_CREATORS: readonly TrackedCreatorSeed[] = [
  { name: "Coin Bureau", youtube_handle: "@CoinBureau", subscribers: "2.6M", focus: "Fundamental analysis, macro, token and ecosystem research" },
  { name: "Andrei Jikh", youtube_handle: "@andreijikh", subscribers: "2.7M", focus: "Personal finance + crypto commentary, macro market views" },
  { name: "Brian Jung", youtube_handle: "@Jungernaut", subscribers: "2.1M", focus: "Crypto plus retail investing, market commentary" },
  { name: "BitBoy Crypto", youtube_handle: "@BitBoyCryptoChannel", subscribers: "1.5M", focus: "Broad altcoin coverage, narratives, news-driven calls" },
  { name: "Altcoin Daily", youtube_handle: "@AltcoinDaily", subscribers: "1.65M", focus: "Daily altcoin picks, BTC/ETH/ADA/SOL, AI tokens" },
  { name: "Alex Becker", youtube_handle: "@AlexBeckersChannel", subscribers: "1.6M", focus: "Bold altcoin calls, AI crypto (RENDER, FET, TAO)" },
  { name: "Discover Crypto", youtube_handle: "@DiscoverCrypto_", subscribers: "1.4M", focus: "SOL ecosystem, broad altcoin analysis" },
  { name: "Altcoin Buzz", youtube_handle: "@AltcoinBuzz", subscribers: "1.4M", focus: "Altcoin news, ecosystem launches, broad crypto coverage" },
  { name: "TechLead", youtube_handle: "@TechLead", subscribers: "1.4M", focus: "Crypto, tech wealth narratives, speculative commentary" },
  { name: "Benjamin Cowen", youtube_handle: "@intothecryptoverse", subscribers: "817K", focus: "Quantitative cycle analysis, BTC/ETH/ADA/DOT" },
  { name: "CryptosRUs", youtube_handle: "@CryptosRUs", subscribers: "810K", focus: "Daily BTC/ETH updates, broad alt coverage" },
  { name: "Crypto Banter", youtube_handle: "@CryptoBanterGroup", subscribers: "795K", focus: "Live trade calls, daily market analysis" },
  { name: "Sheldon Evans", youtube_handle: "@SheldonEvansX", subscribers: "700K", focus: "Altcoin picks, sustainable investing approach" },
  { name: "Crypto Casey", youtube_handle: "@CryptoCasey", subscribers: "660K", focus: "Crypto education, security, onboarding, news commentary" },
  { name: "The Moon Carl", youtube_handle: "@TheMoon", subscribers: "657K", focus: "Bold BTC price targets, TA-based calls" },
  { name: "Lark Davis", youtube_handle: "@TheCryptoLark", subscribers: "640K", focus: "Altcoin gems, SUI/NEAR, portfolio strategy" },
  { name: "Kitco News", youtube_handle: "@kitco", subscribers: "620K", focus: "Macro market news, Bitcoin and institutional crypto commentary" },
  { name: "MMCrypto", youtube_handle: "@MMCryptoTube", subscribers: "620K", focus: "Bitcoin momentum, technical analysis, leverage-style trade views" },
  { name: "EllioTrades Crypto", youtube_handle: "@elliotrades", subscribers: "560K", focus: "Altcoin narratives, growth sectors, speculative rotations" },
  { name: "DataDash", youtube_handle: "@DataDash", subscribers: "511K", focus: "Data-driven macro + crypto, LINK/DOT analysis" },
  { name: "Ivan on Tech", youtube_handle: "@IvanOnTech", subscribers: "500K", focus: "Blockchain education, ecosystem analysis, altcoin cycles" },
  { name: "InvestAnswers", youtube_handle: "@InvestAnswers", subscribers: "450K", focus: "Data-driven buy/sell calls with explicit targets" },
  { name: "Paul Barron Network", youtube_handle: "@PaulBarronNetwork", subscribers: "420K", focus: "Crypto news, token narratives, ecosystem interviews" },
  { name: "Anthony Pompliano", youtube_handle: "@AnthonyPompliano", subscribers: "420K", focus: "Bitcoin, macro, policy, institutional adoption" },
  { name: "Crypto Capital Venture", youtube_handle: "@CryptoCapitalVenture", subscribers: "402K", focus: "ADA champion, mid-cap alt predictions" },
  { name: "Austin Hilton", youtube_handle: "@AustinHilton", subscribers: "359K", focus: "Daily altcoin plays, DOGE, meme coins" },
  { name: "Bankless", youtube_handle: "@Bankless", subscribers: "310K", focus: "Ethereum, DeFi, crypto policy, on-chain investing" },
  { name: "Michael Wrubel", youtube_handle: "@MichaelWrubel", subscribers: "315K", focus: "Undervalued alts, honest quick reviews" },
  { name: "Satoshi Stacker", youtube_handle: "@StackerSatoshi", subscribers: "300K", focus: "Daily BTC + altcoin picks, AI/gaming crypto" },
  { name: "Crypto Zombie", youtube_handle: "@CryptoZombie", subscribers: "263K", focus: "Daily altcoin alerts, specific entries" },
  { name: "Crypto Jebb", youtube_handle: "@CryptoJebb", subscribers: "248K", focus: "TA chart patterns, price targets" },
  { name: "The Modern Investor", youtube_handle: "channel/UC-5HLi3buMzdxjdTdic3Aig", subscribers: "229K", focus: "Daily crypto investor updates, macro framing, risk management" },
  { name: "Raoul Pal", youtube_handle: "@RaoulGMI", subscribers: "220K", focus: "Macro cycles, institutional crypto theses, long-duration narratives" },
  { name: "CryptoBusy", youtube_handle: "@CryptoBusy", subscribers: "220K", focus: "Altcoin research, trend analysis, investor education" },
  { name: "Blockworks Macro", youtube_handle: "@BlockworksMacro", subscribers: "210K", focus: "Macro, policy, institutional crypto narratives" },
  { name: "Crypto Rover", youtube_handle: "@CryptoRover", subscribers: "210K", focus: "Daily BTC/SOL calls, altcoin analysis" },
  { name: "Wolf of All Streets", youtube_handle: "@scottmelker", subscribers: "180K", focus: "Trading, macro interviews, Bitcoin and altcoin setups" },
  { name: "Taiki Maeda", youtube_handle: "@TaikiMaeda2", subscribers: "180K", focus: "DeFi, yield rotations, ecosystem-specific opportunities" },
  { name: "VirtualBacon", youtube_handle: "@VirtualBacon", subscribers: "170K", focus: "Portfolio construction, macro + crypto allocations, risk-managed ideas" },
  { name: "Kevin Svenson", youtube_handle: "@KevinSvenson", subscribers: "140K", focus: "Bitcoin technical analysis, cycle timing, breakout setups" },
  { name: "Digital Asset News", youtube_handle: "@DigitalAssetNewsDAN", subscribers: "120K", focus: "Crypto investing commentary, risk management, portfolio views" },
  { name: "Crypto Kirby Trading", youtube_handle: "@CryptoKirbyTrading", subscribers: "120K", focus: "Technical analysis, swing trade setups, Bitcoin and majors" },
  { name: "Mikybull Crypto", youtube_handle: "@MikybullCrypto", subscribers: "110K", focus: "Bitcoin and altcoin technical analysis, swing setups" },
  { name: "Miles Deutscher", youtube_handle: "@milesdeutscher1357", subscribers: "100K", focus: "Specific entries/exits, SUI/INJ/RENDER/FET" },
  { name: "The Defiant", youtube_handle: "@TheDefiant", subscribers: "95K", focus: "DeFi news, protocol activity, on-chain ecosystem coverage" },
  { name: "ReadySetCrypto", youtube_handle: "@ReadySetCrypto", subscribers: "95K", focus: "Crypto education, portfolio strategy, market views" },
  { name: "Empire by Blockworks", youtube_handle: "@EmpireShow", subscribers: "90K", focus: "Crypto founders, infrastructure, policy and market structure" },
  { name: "Crypto Jon", youtube_handle: "@CryptoJon", subscribers: "80K", focus: "Small-cap altcoin narratives, momentum ideas" },
  { name: "Unchained", youtube_handle: "@unchainedcrypto", subscribers: "75K", focus: "Crypto policy, narratives, infrastructure, founder interviews" },
  { name: "Laura Shin", youtube_handle: "@LauraShin", subscribers: "70K", focus: "Crypto journalism, market structure, major ecosystem interviews" },
  { name: "Jacob Crypto Bury", youtube_handle: "@JacobCryptoBury", subscribers: "58K", focus: "Early small-cap gems, PENDLE/AR" },
  { name: "Johnny Harris", youtube_handle: "@johnnyharris", subscribers: "6.0M", focus: "Geopolitics and macro narratives intersecting with Bitcoin and markets" },
  { name: "99Bitcoins", youtube_handle: "@99Bitcoins", subscribers: "720K", focus: "Bitcoin and crypto education, mining, beginner-focused explainers" },
] as const;

export const TRACKED_CREATOR_COUNT = TRACKED_CREATORS.length;
