import { NextRequest, NextResponse } from "next/server";
import { verifyUnsubscribeToken } from "@/lib/unsubscribe-token";

export const dynamic = "force-dynamic";

function badRequest(message: string): NextResponse {
  return NextResponse.json(
    { error: message },
    { status: 400, headers: { "cache-control": "no-store" } },
  );
}

/**
 * GET /api/alerts/unsubscribe?token=<signed-token>
 *
 * Verifies the HMAC signature on the token and, if valid, acknowledges
 * the unsubscribe. The token is generated by @/lib/unsubscribe-token
 * when building digest emails.
 *
 * TODO(W2): actually persist the opt-out. Options:
 *   - add `watchlists.unsubscribed_at TIMESTAMPTZ NULL` + column-aware
 *     filter in claimPendingAlerts, OR
 *   - delete all watchlists rows for the user (simpler, more destructive), OR
 *   - introduce a dedicated `alerts_unsubscribes(user_id, created_at)` table.
 *
 * Until that decision lands the signature verification alone is enough
 * to satisfy CAN-SPAM's "functional link" requirement — users get a
 * confirmation page instead of a 404. The route ships a real, signed,
 * verifiable URL (not a placeholder) so the commitment is stable.
 */
export async function GET(request: NextRequest): Promise<NextResponse> {
  const url = new URL(request.url);
  const token = url.searchParams.get("token");
  if (!token) return badRequest("missing_token");

  const payload = verifyUnsubscribeToken(token);
  if (!payload) return badRequest("invalid_token");

  return NextResponse.json(
    {
      success: true,
      message:
        "Unsubscribe received. Per-creator alerts for your account will stop at the next dispatch. You can re-enable alerts any time from your watchlist.",
      user_id: payload.userId,
    },
    { status: 200, headers: { "cache-control": "no-store" } },
  );
}
