import {
  buildMediaTaskEnvelope,
  buildMediaToolInheritanceReceipt,
  type MediaArtifactReceipt,
} from "../../src/lib/agent-toolbox-contract";
import {
  CANONICAL_DESIGN_BUNDLE_PATH,
  CANONICAL_DESIGN_MD_PATH,
  CANONICAL_DESIGN_PACK_LOGO_PATH,
  FRONTEND_DESIGN_SKILL_PATH,
} from "../../src/lib/design-bundle-enforcement";

export function validCanonicalMediaArtifact(channel: "x" | "linkedin" = "x"): MediaArtifactReceipt {
  const imageAgent = channel === "x" ? "callscore-x-image-agent" : "callscore-linkedin-image-agent";
  const headAgent = channel === "x" ? "callscore-x-head" : "callscore-linkedin-head";
  const tools = ["visual-proof-object-designer", "visual-layout-spec-writer", "svg-renderer", "png-rasterizer", "visual-qa"];
  const envelope = buildMediaTaskEnvelope({
    task_id: `media-task-${channel}`,
    workflow_id: `wf-${channel}-owned-public`,
    parent_agent_id: headAgent,
    target_agent_id: imageAgent,
    channel,
    media_type: "image",
    objective: "Create a receipt-backed CallScore proof-object image.",
    source_artifact_refs: ["artifact://copy"],
    source_evidence_refs: ["artifact://evidence"],
    copy_context_refs: ["artifact://copy"],
    visual_brief_ref: "receipt://visual_brief_receipt.v1",
    platform_constraints: { dimensions: "1200x675", max_file_size: "5MB", format: "png" },
    required_tools: tools,
    output_schema: "callscore.media_artifact.v2",
    execution_mode: "live_owned_public",
  });
  const inheritance = buildMediaToolInheritanceReceipt({
    task_id: `media-task-${channel}`,
    parent_agent_id: headAgent,
    media_agent_id: imageAgent,
    workflow_id: `wf-${channel}-owned-public`,
    channel,
    media_type: "image",
    requested_tools: envelope.required_tools,
    execution_mode: "live_owned_public",
    tool_versions: { "png-rasterizer": "ffmpeg-local" },
  });
  const hash = "a".repeat(64);
  const occlusion = {
    schema: "callscore.brand_lockup_occlusion_check.v1" as const,
    status: "passed" as const,
    media_path: "card.png",
    media_sha256: hash,
    brand_asset_path: CANONICAL_DESIGN_PACK_LOGO_PATH,
    brand_asset_sha256: "b".repeat(64),
    brand_bbox: [1296, 72, 196, 80],
    brand_safe_zone_bbox: [1272, 48, 244, 128],
    intersecting_line_segments: [],
    intersecting_borders: [],
    intersecting_visual_elements: [],
    min_clearance_px: 32,
    required_min_clearance_px: 24,
    preferred_clearance_px: 32,
    top_right_crop_path: "crop.png",
    debug_overlay_path: "debug.png",
    brand_lockup_present: true,
    brand_lockup_position: "top_right" as const,
    brand_lockup_safe_zone_clear: true,
    brand_lockup_occlusion_free: true,
    no_hairline_intersects_brand: true,
    tagline_readable: true,
    logo_not_clipped: true,
    pass: true,
  };
  const checks = Object.fromEntries([
    "uses_editorial_terminal_style",
    "uses_ink_surface_ramp",
    "uses_sparse_ochre_accent",
    "uses_serif_editorial_hierarchy",
    "uses_mono_numeric_evidence_layers",
    "uses_rectangular_panels",
    "uses_1px_hairlines",
    "uses_provenance_evidence_hierarchy",
    "avoids_generic_saas_card",
    "avoids_neon_crypto_cliche",
    "avoids_ai_gloss",
    "avoids_old_noncanonical_style",
    "brand_lockup_present",
    "brand_lockup_position_top_right",
    "brand_lockup_safe_zone_clear",
    "brand_lockup_occlusion_free",
    "no_hairline_intersects_brand",
    "tagline_readable",
    "logo_not_clipped",
  ].map((key) => [key, true]));
  const designBundleReceipt = {
    schema: "callscore.design_bundle_reference_receipt.v1" as const,
    workflow_id: `wf-${channel}-owned-public`,
    agent_id: imageAgent,
    channel,
    artifact_id: `artifact-${channel}`,
    media_task_id: `media-task-${channel}`,
    design_bundle_path: CANONICAL_DESIGN_BUNDLE_PATH,
    design_bundle_sha256: "c".repeat(64),
    design_md_path: CANONICAL_DESIGN_MD_PATH,
    design_md_sha256: "d".repeat(64),
    canonical_logo_path: CANONICAL_DESIGN_PACK_LOGO_PATH,
    canonical_logo_sha256: "b".repeat(64),
    example_images_used_as_reference: [],
    frontend_design_skill_path: FRONTEND_DESIGN_SKILL_PATH,
    frontend_design_skill_sha256: "e".repeat(64),
    loaded_before_generation: true,
    content_reference_mode: "paths_ids_hashes_only" as const,
    created_at_utc: "2026-07-09T00:00:00.000Z",
  };
  const alignmentReceipt = {
    schema: "callscore.website_design_alignment_receipt.v2" as const,
    workflow_id: `wf-${channel}-owned-public`,
    agent_id: imageAgent,
    channel,
    artifact_id: `artifact-${channel}`,
    media_artifact_id: `media-${channel}`,
    final_media_path: "card.png",
    final_media_sha256: hash,
    design_bundle_reference_receipt_id: `design-${channel}`,
    checks,
    style_failures: [],
    status: "passed" as const,
    created_at_utc: "2026-07-09T00:00:00.000Z",
  };
  const brandingReceipt = {
    schema: "callscore.branding_receipt.v2" as const,
    channel,
    artifact_id: `artifact-${channel}`,
    media_artifact_id: `media-${channel}`,
    branding_applied: true,
    brand_asset_source: "canonical_design_pack" as const,
    brand_asset_path: CANONICAL_DESIGN_PACK_LOGO_PATH,
    brand_asset_sha256: "b".repeat(64),
    placement: "top_right" as const,
    top_right_brand_crop_path: "crop.png",
    top_right_brand_crop_sha256: "f".repeat(64),
    top_right_brand_crop_visible: true,
    final_media_path: "card.png",
    final_media_sha256: hash,
    created_by_agent_id: imageAgent,
    channel_head_agent_id: headAgent,
    parent_harness_rendered: false,
    hardcoded_brand_text_used: false,
    fallback_wordmark_used: false,
    fallback_icon_only_logo_used: false,
    brand_lockup_safe_zone_clear: true,
    brand_lockup_occlusion_free: true,
    no_hairline_intersects_brand: true,
    tagline_readable: true,
    logo_not_clipped: true,
    brand_lockup_occlusion_check: occlusion,
    content_reference_mode: "paths_ids_hashes_only" as const,
    created_at_utc: "2026-07-09T00:00:00.000Z",
  };
  return {
    schema: "callscore.media_artifact_receipt.v2",
    artifact_id: `artifact-${channel}`,
    media_artifact_id: `media-${channel}`,
    created_by_agent_id: imageAgent,
    channel_head_agent_id: headAgent,
    workflow_id: `wf-${channel}-owned-public`,
    media_type: "image",
    source_copy_artifact_id: `copy-${channel}`,
    source_visual_brief_id: `visual-brief-${channel}`,
    source_evidence_paths: ["evidence.json"],
    media_task_envelope: envelope,
    media_tool_inheritance_receipt: inheritance,
    tool_inheritance_receipt_id: `inheritance-${channel}`,
    tools_used: tools,
    renderer_used: "png-rasterizer",
    input_spec_path: "visual-spec.json",
    output_paths: ["card.png"],
    mime_type: "image/png",
    dimensions: { width: 1200, height: 675 },
    duration_seconds: null,
    codec: null,
    file_size_bytes: 120000,
    sha256: hash,
    alt_text: "Receipt-backed CallScore proof-object image.",
    visual_qa_receipt_id: `visual-qa-${channel}`,
    copy_visual_coherence_receipt_id: `copy-visual-${channel}`,
    design_bundle_reference_receipt: designBundleReceipt,
    website_design_alignment_receipt: alignmentReceipt,
    branding_receipt: brandingReceipt,
    brand_lockup_occlusion_check: occlusion,
    visual_qa_geometry: {
      all_text_container_pair_checks_complete: true,
      text_container_pair_check_count: 42,
      text_container_expected_pair_count: 42,
      text_container_collision_count: 0,
      text_container_collisions: [],
      text_container_containment_failure_count: 0,
      footer_containment_failure_count: 0,
      footer_sibling_collision_count: 0,
      footer_wrapped_text_count: 0,
      caveat_to_footer_gap_px: 24,
      minimum_required_section_gap_px: 24,
      footer_minimum_inline_clearance_px: 16,
      footer_required_inline_clearance_px: 16,
      minimum_effective_font_size_at_375_px: 12,
      minimum_required_effective_font_size_px: 12,
      rendered_pixel_inspection: "passed",
      artifact_sha256: hash,
      evidence_path: "checks/layout-measurements.json",
      evidence_sha256: "9".repeat(64),
      source_viewport_width_px: 1200,
      source_viewport_height_px: 675,
      preview_viewport_width_px: 375,
      parent_rendered_pixel_reviewed: true,
      parent_review_receipt_id: `parent-pixel-review-${channel}`,
      parent_reviewer_agent_id: "callscore-orchestrator-head",
    },
    visual_proof_object_present: true,
    hardcoded_runtime_media: false,
    parent_harness_rendered: false,
    status: "ready",
  };
}
